<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert ke master_items
        $items = [
            // ========== GENTLE BABY PRODUCTS ==========
            
            // Deep Sleep - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-DS',
                'name_item' => 'Gentle Baby Deep Sleep 10ml',
                'description_item' => 'Minyak bayi untuk membantu bayi tidur nyenyak',
                'ingredient_item' => 'Minyak Lavender, Minyak Chamomile, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "deep-sleep-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-DS-01',
                'name_item' => 'Gentle Baby Deep Sleep 30ml',
                'description_item' => 'Minyak bayi untuk membantu bayi tidur nyenyak',
                'ingredient_item' => 'Minyak Lavender, Minyak Chamomile, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "deep-sleep-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-DS-02',
                'name_item' => 'Gentle Baby Deep Sleep 100ml',
                'description_item' => 'Minyak bayi untuk membantu bayi tidur nyenyak',
                'ingredient_item' => 'Minyak Lavender, Minyak Chamomile, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "deep-sleep-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-DS-03',
                'name_item' => 'Gentle Baby Deep Sleep 250ml',
                'description_item' => 'Minyak bayi untuk membantu bayi tidur nyenyak',
                'ingredient_item' => 'Minyak Lavender, Minyak Chamomile, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "deep-sleep-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Joy - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-JOY',
                'name_item' => 'Gentle Baby Joy 10ml',
                'description_item' => 'Minyak bayi untuk meningkatkan mood anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "joy-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-JOY-01',
                'name_item' => 'Gentle Baby Joy 30ml',
                'description_item' => 'Minyak bayi untuk meningkatkan mood anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "joy-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-JOY-02',
                'name_item' => 'Gentle Baby Joy 100ml',
                'description_item' => 'Minyak bayi untuk meningkatkan mood anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "joy-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-JOY-03',
                'name_item' => 'Gentle Baby Joy 250ml',
                'description_item' => 'Minyak bayi untuk meningkatkan mood anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "joy-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Cough n Flu - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-CNF',
                'name_item' => 'Gentle Baby Cough n Flu 10ml',
                'description_item' => 'Minyak bayi yang membantu meredakan batuk dan flu pada anak bayi',
                'ingredient_item' => 'Minyak Eucalyptus, Minyak Lavender, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "cough-flu-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-CNF-01',
                'name_item' => 'Gentle Baby Cough n Flu 30ml',
                'description_item' => 'Minyak bayi yang membantu meredakan batuk dan flu pada anak bayi',
                'ingredient_item' => 'Minyak Eucalyptus, Minyak Lavender, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "cough-flu-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-CNF-02',
                'name_item' => 'Gentle Baby Cough n Flu 100ml',
                'description_item' => 'Minyak bayi yang membantu meredakan batuk dan flu pada anak bayi',
                'ingredient_item' => 'Minyak Eucalyptus, Minyak Lavender, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "cough-flu-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-CNF-03',
                'name_item' => 'Gentle Baby Cough n Flu 250ml',
                'description_item' => 'Minyak bayi yang membantu meredakan batuk dan flu pada anak bayi',
                'ingredient_item' => 'Minyak Eucalyptus, Minyak Lavender, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "cough-flu-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Bye Bugs - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-BB',
                'name_item' => 'Gentle Baby Bye Bugs 10ml',
                'description_item' => 'Minyak bayi yang mengusir nyamuk dan serangga dengan aman',
                'ingredient_item' => 'Minyak Citronella, Minyak Lemongrass, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "bye-bugs.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-BB-01',
                'name_item' => 'Gentle Baby Bye Bugs 30ml',
                'description_item' => 'Minyak bayi untuk meningkatkan mood anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "bye-bugs-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-BB-02',
                'name_item' => 'Gentle Baby Bye Bugs 100ml',
                'description_item' => 'Minyak bayi untuk meningkatkan mood anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "bye-bugs-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Gimme Food - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-GF',
                'name_item' => 'Gentle Baby Gimme Food 10ml',
                'description_item' => 'Minyak untuk meningkatkan nafsu makan pada bayi',
                'ingredient_item' => 'Minyak Chamomile, Minyak Zinc Oxide, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "gimme-food-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-GF-01',
                'name_item' => 'Gentle Baby Gimme Food 30ml',
                'description_item' => 'Minyak untuk meningkatkan nafsu makan pada bayi',
                'ingredient_item' => 'Minyak Chamomile, Minyak Zinc Oxide, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "gimme-food-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-GF-02',
                'name_item' => 'Gentle Baby Gimme Food 100ml',
                'description_item' => 'Minyak untuk meningkatkan nafsu makan pada bayi',
                'ingredient_item' => 'Minyak Chamomile, Minyak Zinc Oxide, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "gimme-food-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-GF-03',
                'name_item' => 'Gentle Baby Gimme Food 250ml',
                'description_item' => 'Minyak untuk meningkatkan nafsu makan pada bayi',
                'ingredient_item' => 'Minyak Chamomile, Minyak Zinc Oxide, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "gimme-food-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Tummy Calmer - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-TC',
                'name_item' => 'Gentle Baby Tummy Calmer 10ml',
                'description_item' => 'Minyak bayi untuk perut kembung dan kolik',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "tummy-calmer-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-TC-01',
                'name_item' => 'Gentle Baby Tummy Calmer 30ml',
                'description_item' => 'Minyak bayi untuk perut kembung dan kolik',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "tummy-calmer-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-TC-02',
                'name_item' => 'Gentle Baby Tummy Calmer 100ml',
                'description_item' => 'Minyak bayi untuk perut kembung dan kolik',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "tummy-calmer-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-TC-03',
                'name_item' => 'Gentle Baby Tummy Calmer 250ml',
                'description_item' => 'Minyak bayi untuk perut kembung dan kolik',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "tummy-calmer-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // LDR Booster - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-LDR',
                'name_item' => 'Gentle Baby LDR Booster 10ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "ldr-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-LDR-01',
                'name_item' => 'Gentle Baby LDR Booster 30ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "ldr-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-LDR-02',
                'name_item' => 'Gentle Baby LDR Booster 100ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "ldr-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-LDR-03',
                'name_item' => 'Gentle Baby LDR Booster 250ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "ldr-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Massage Your Baby - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-MYB',
                'name_item' => 'Gentle Baby Massage Your Baby 10ml',
                'description_item' => 'Minyak bayi untuk pijat bayi',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "massage-your-baby-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-MYB-01',
                'name_item' => 'Gentle Baby Massage Your Baby 30ml',
                'description_item' => 'Minyak bayi untuk pijat bayi',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "massage-your-baby-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-MYB-02',
                'name_item' => 'Gentle Baby Massage Your Baby 100ml',
                'description_item' => 'Minyak bayi untuk pijat bayi',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "massage-your-baby-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-MYB-03',
                'name_item' => 'Gentle Baby Massage Your Baby 250ml',
                'description_item' => 'Minyak bayi untuk pijat bayi',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "massage-your-baby-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // Immboost - 10ml, 30ml, 100ml, 250ml
            [
                'company_id' => 3,
                'code_item' => 'GB-IMB',
                'name_item' => 'Gentle Baby Immboost 10ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '10ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 12000,
                'picture_item' => "immboost-10ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-IMB-01',
                'name_item' => 'Gentle Baby Immboost 30ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 25000,
                'picture_item' => "immboost-30ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-IMB-02',
                'name_item' => 'Gentle Baby Immboost 100ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '100ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 30000,
                'picture_item' => "immboost-100ml.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-IMB-03',
                'name_item' => 'Gentle Baby Immboost 250ml',
                'description_item' => 'Minyak bayi untuk meningkatkan daya tahan tubuh anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '250ml',
                'contain_item' => '1 botol minyak bayi',
                'costprice_item' => 100000,
                'picture_item' => "immboost-250ml.jpg",
                'status_item' => 'active',
                'is_reseller_babyspa' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ========== GENTLE BABY TWIN PACKS ==========
            [
                'company_id' => 3,
                'code_item' => 'GB-TP-CC',
                'name_item' => 'Gentle Twin Pack Common Cold',
                'description_item' => 'Minyak bayi untuk meningkatkan menghilangkan kedinginan anak',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 pack minyak bayi',
                'costprice_item' => 29000,
                'picture_item' => "twin-pack-common-cold.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'GB-TP-NB',
                'name_item' => 'Gentle Twin Pack New Born',
                'description_item' => 'Minyak bayi untuk bayi baru lahir',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 pack minyak bayi',
                'costprice_item' => 29000,
                'picture_item' => "twin-pack-newborn.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],            
            [
                'company_id' => 3,
                'code_item' => 'GB-TP-TV',
                'name_item' => 'Gentle Twin Pack Travel Pack',
                'description_item' => 'Minyak bayi untuk berpergian jauh',
                'ingredient_item' => 'Minyak Peppermint, Minyak Fennel, Minyak Kelapa',
                'netweight_item' => '30ml',
                'contain_item' => '1 pack minyak bayi',
                'costprice_item' => 29000,
                'picture_item' => "twin-pack-travelpack.jpg",
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // ========== HEALO PRODUCTS ==========
            [
                'company_id' => 3,
                'code_item' => 'HL-001',
                'name_item' => 'Healo Aeris',
                'description_item' => 'HEALO by GentleLiving adalah aromatherapy roll-on alami yang aman untuk seluruh keluarga — dari bayi baru lahir hingga dewasa.',
                'ingredient_item' => 'Grapeseed Oil (97%),Blend RC-type EO: Eucalyptus, Myrtle, Lavender, Peppermint, ',
                'netweight_item' => '10ml',
                'contain_item' => '1 roll on aromatherapy',
                'costprice_item' => 8000,
                'picture_item' => 'healo-aeris.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'HL-002',
                'name_item' => 'Healo Stiffin',
                'description_item' => 'HEALO by GentleLiving adalah aromatherapy roll-on alami yang aman untuk seluruh keluarga — dari bayi baru lahir hingga dewasa.',
                'ingredient_item' => ' Grapeseed Oil, Wintergreen & Copaiba',
                'netweight_item' => '10ml',
                'contain_item' => '1 roll on aromatherapy',
                'costprice_item' => 8000,
                'picture_item' => 'healo-stiffin.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'HL-003',
                'name_item' => 'Healo Fresh Guard',
                'description_item' => 'HEALO by GentleLiving adalah aromatherapy roll-on alami yang aman untuk seluruh keluarga — dari bayi baru lahir hingga dewasa. ',
                'ingredient_item' => ' Grapeseed Oil, Eucalyptus, Lemon, Peppermint, Cajuput, Clove',
                'netweight_item' => '10ml',
                'contain_item' => '1 roll on aromatherapy',
                'costprice_item' => 8000,
                'picture_item' => 'healo-fresh-guard.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'HL-004',
                'name_item' => 'Healo Teething',
                'description_item' => 'Aromatherapy roll-on alami yang diformulasikan khusus untuk membantu meredakan ketidaknyamanan bayi saat masa teething.',
                'ingredient_item' => 'Grapeseed Oil, Chamomile, Lavender, Clove, Peppermint',
                'netweight_item' => '10ml',
                'contain_item' => '1 roll on aromatherapy',
                'costprice_item' => 8000,
                'picture_item' => 'healo-teething.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 3,
                'code_item' => 'HL-005',
                'name_item' => 'Healo Starter Pack by Gentle Living – Paket 3 Roll On Aromaterapi (AERIS, STIFFIN, FRESH GUARD)',
                'description_item' => 'Healo Starter Pack by GentleLiving (Isi 3 x 10 ml) Paket aromaterapi roll-on lengkap untuk seluruh keluarga.',
                'ingredient_item' => ' Grapeseed Oil, Eucalyptus, Lemon, Peppermint, Cajuput, Clove',
                'netweight_item' => '10ml',
                'contain_item' => '1 roll on aromatherapy',
                'costprice_item' => 27000,
                'picture_item' => 'healo-starter-pack.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Mamina Products
            
            // jeruk nipis
            [
                'company_id' => 2,
                'code_item' => 'MM-JN-01',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Jeruk nipis 5 kantong ',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Jahe, Kunyit, Jeruk Nipis',
                'netweight_item' => '5 kantong x 2,5g',
                'contain_item' => '1 box berisi 5 kantong teh',
                'costprice_item' => 12000,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 2,
                'code_item' => 'MM-JN-02',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Jeruk Nipis 10 kantong',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Kelor, Jahe,  Kunyit, Temulawak, Jeruk Nipis',
                'netweight_item' => '10 kantong x 2,5g',
                'contain_item' => '1 box berisi 10 kantong teh',
                'costprice_item' => 18000,
                'picture_item' =>  'mamina-01.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 2,
                'code_item' => 'MM-JN-03',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Jeruk Nipis 20 kantong',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Kelor, Jahe,  Kunyit, Temulawak, Jeruk Nipis',
                'netweight_item' => '20 kantong x 2,5g',
                'contain_item' => '1 box berisi 20 kantong teh',
                'costprice_item' => 30000,
                'picture_item' => 'mamina-02.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // original
            [
                'company_id' => 2,
                'code_item' => 'MM-OR-01',
                'name_item' => 'Mamina Seduhan Herbal | Rasa original 5 kantong ',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Jahe, Kunyit, Jeruk Nipis',
                'netweight_item' => '5 kantong x 2,5g',
                'contain_item' => '1 box berisi 5 kantong teh',
                'costprice_item' => 12000,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 2,
                'code_item' => 'MM-OR-02',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Original 10 kantong',
                'description_item' => 'Mamina Seduhan Herbal Isi 10 Kantong Rasa Original Mamina Seduhan Herbal adalah Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya. ',
                'ingredient_item' => 'katuk, kapulaga, kelor, jahe, kunyit, temulawak, sereh, cengkeh',
                'netweight_item' => '10 kantong x 2,5g',
                'contain_item' => '1 box berisi 10 kantong teh',
                'costprice_item' => 18000,
                'picture_item' => 'mamina-03.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 2,
                'code_item' => 'MM-OR-03',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Original 20 kantong',
                'description_item' => 'Mamina Seduhan Herbal Isi 10 Kantong Rasa Original Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya. ',
                'ingredient_item' => 'katuk, kapulaga, kelor, jahe, kunyit, temulawak, sereh, cengkeh',
                'netweight_item' => '20 kantong x 2,5g',
                'contain_item' => '1 box berisi 20 kantong teh',
                'costprice_item' => 30000,
                'picture_item' => 'mamina-04.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            
            // belimbing wuluh
            [
                'company_id' => 2,
                'code_item' => 'MM-BW-01',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Belimbing Wuluh 5 kantong',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Jahe, Kunyit, Jeruk Nipis',
                'netweight_item' => '5 kantong x 2,5g',
                'contain_item' => '1 box berisi 5 kantong teh',
                'costprice_item' => 12000,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 2,
                'code_item' => 'MM-BW-02',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Belimbing Wuluh 10 kantong',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Jahe, Kunyit, Jeruk Nipis',
                'netweight_item' => '10 kantong x 2,5g',
                'contain_item' => '1 box berisi 10 kantong teh',
                'costprice_item' => 18000,
                'picture_item' => 'mamina-05.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 2,
                'code_item' => 'MM-BW-03',
                'name_item' => 'Mamina Seduhan Herbal | Rasa Belimbing Wuluh 20 kantong',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Jahe, Kunyit, Jeruk Nipis',
                'netweight_item' => '20 kantong x 2,5g',
                'contain_item' => '1 box berisi 20 kantong teh',
                'costprice_item' => 18000,
                'picture_item' => 'mamina-06.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
                        
            // 3 kantong
            [
                'company_id' => 2,
                'code_item' => 'MM-MIX-01',
                'name_item' => 'Mamina Seduhan Herbal | (1 Box - 3 Kantong) Mix Rasa',
                'description_item' => 'Mamina Seduhan Herbal adalah  Seduhan herbal pelancar ASI ini bukan sekadar minuman, tetapi ritual yang mendukung perjalanan seorang ibu dalam memberikan yang terbaik bagi buah hatinya.',
                'ingredient_item' => 'Katuk, Kapulaga, Belimbing Wuluh, Jahe, Kunyit, Jeruk Nipis',
                'netweight_item' => '3 kantong x 2,5g',
                'contain_item' => '1 box berisi 3 kantong teh',
                'costprice_item' => 5000,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Nyam MPASI Products
            [
                'company_id' => 1,
                'code_item' => 'NY-AHA',
                'name_item' => 'Nyam Abon Hati Ayam',
                'description_item' => 'Delicious chicken liver floss for babies',
                'ingredient_item' => 'Chicken liver, spices',
                'netweight_item' => '50g',
                'contain_item' => 'Iron, protein',
                'costprice_item' => 22000,
                'picture_item' => 'abon-hati-ayam.jpg', 
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-BFP',
                'name_item' => 'Nyam Beef Pudding',
                'description_item' => 'Delicious beef pudding for babies',
                'ingredient_item' => 'Beef, milk, organic ingredients',
                'netweight_item' => '200g',
                'contain_item' => 'High protein, vitamins',
                'costprice_item' => 20000,
                'picture_item' => 'beef-pudding.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [

                'company_id' => 1,
                'code_item' => 'NY-CP',
                'name_item' => 'Nyam Chicken Pudding',
                'description_item' => 'Nutritious chicken pudding for babies',
                'ingredient_item' => 'Chicken, milk, organic ingredients',
                'netweight_item' => '200g',
                'contain_item' => 'High protein, vitamins',
                'costprice_item' => 15000,
                'picture_item' => 'chicken-pudding.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-CBB',
                'name_item' => 'Nyam Ciki Bone Broth',
                'description_item' => 'Nutritious bone broth for babies',
                'ingredient_item' => 'Bone broth, vegetables',
                'netweight_item' => '250ml',
                'contain_item' => 'Collagen, minerals',
                'costprice_item' => 19000,
                'picture_item' => 'ciki-bone-broth.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-FMB',
                'name_item' => 'Nyam Full Meal Bolognese',
                'description_item' => 'Nutritious full meal for babies',
                'ingredient_item' => 'Tomatoes, Pasta',
                'netweight_item' => '100ml',
                'contain_item' => '-',
                'costprice_item' => 20000,
                'picture_item' => 'pasta-bolognese.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-FMDBK',
                'name_item' => 'Nyam Full Meal Dori Bumbu Kuning',
                'description_item' => 'Nutritious full meal for babies',
                'ingredient_item' => 'Dory fish fillet, Lime',
                'netweight_item' => '100g',
                'contain_item' => '-',
                'costprice_item' => 16000,
                'picture_item' => 'dori-bumbu-kuning.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-FMHABK',
                'name_item' => 'Nyam Full Meal Hati Ayam Bumbu Kuning',
                'description_item' => 'Nutritious full meal for babies',
                'ingredient_item' => 'Chicken liver, Lime',
                'netweight_item' => '100ml',
                'contain_item' => '-',
                'costprice_item' => 15000,
                'picture_item' => 'hati-ayam-bumbu-kuning.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-FMNUAT',
                'name_item' => 'Nyam Full Meal Nasi Uduk Ayam Telor',
                'description_item' => 'Nutritious full meal for babies',
                'ingredient_item' => 'Chicken, Nasi Uduk, Eggs',
                'netweight_item' => '100ml',
                'contain_item' => '-',
                'costprice_item' => 15000,
                'picture_item' => 'nasi-uduk.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-FMOO',
                'name_item' => 'Nyam Full Meal Opor Otak',
                'description_item' => 'Nutritious full meal for babies',
                'ingredient_item' => 'Beef brain, coconut milk, rice, spices',
                'netweight_item' => '100ml',
                'contain_item' => '-',
                'costprice_item' => 17000,
                'picture_item' => 'full-meal-opor-otak.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-HAL',
                'name_item' => 'Nyam Hati Ayam Lengkuas',
                'description_item' => 'Chicken liver that are processed with this typical galangal spice have a soft texture inside and a crispy exterior',
                'ingredient_item' => 'Chicken liver, galangal, sea salt, spices',
                'netweight_item' => '100g',
                'contain_item' => '-',
                'costprice_item' => 20000,
                'picture_item' => 'hati-ayam-lengkuas.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-IDC',
                'name_item' => 'Nyam Ice Dairy Choco',
                'description_item' => 'Various flavored ice cream for babies',
                'ingredient_item' => 'Milk, natural fruits',
                'netweight_item' => '50g',
                'contain_item' => 'Vitamins, natural sweeteners',
                'costprice_item' => 13200,
                'picture_item' => 'ice-dairy-choco.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-IDO',
                'name_item' => 'Nyam Ice Dairy Ori',
                'description_item' => 'Various flavored ice cream for babies',
                'ingredient_item' => 'Milk, natural fruits',
                'netweight_item' => '50g',
                'contain_item' => 'Vitamins, natural sweeteners',
                'costprice_item' => 13200,
                'picture_item' => 'ice-dairy-ori.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-INDC',
                'name_item' => 'Nyam Ice Non-Dairy Choco',
                'description_item' => 'Various flavored ice cream for babies',
                'ingredient_item' => 'Coconut Milk, natural fruits',
                'netweight_item' => '50g',
                'contain_item' => 'Vitamins, natural sweeteners',
                'costprice_item' => 13200,
                'picture_item' => 'ice-non-dairy-choco.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-INDO',
                'name_item' => 'Nyam Ice Non-Dairy Ori',
                'description_item' => 'Various flavored ice cream for babies',
                'ingredient_item' => 'Coconut Milk, natural fruits',
                'netweight_item' => '50g',
                'contain_item' => 'Vitamins, natural sweeteners',
                'costprice_item' => 13200,
                'picture_item' => 'ice-cream.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-JAU',
                'name_item' => 'Nyam Jantung Ayam Ungkep',
                'description_item' => 'Chicken liver cooked with a spice mix using selected herbs. Tender texture with a savory taste characteristic of traditional seasonings.',
                'ingredient_item' => 'Chicken liver, sea salt, spices',
                'netweight_item' => '100g',
                'contain_item' => '-',
                'costprice_item' => 20000,
                'picture_item' => 'jantung-ayam-ungkep.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],            
            [
                'company_id' => 1,
                'code_item' => 'NY-KCN',
                'name_item' => 'Nyam Kiddy Chicken Nugget',
                'description_item' => 'Selected cuts of minced chicken, these nuggets have a soft texture inside and a crispy coating outside',
                'ingredient_item' => 'chicken, eggs, breadcrumbs, spice',
                'netweight_item' => '150g',
                'contain_item' => '-',
                'costprice_item' => 25000,
                'picture_item' => 'kiddy-chicken-nugget.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-LDK',
                'name_item' => 'Nyam Lapis Daging Koyor',
                'description_item' => 'A special Indonesian dish that combines selected beef and koyor (beef tendons) with typical archipelago spices. With a sweet and savory flavor, it presents a soft and chewy texture.',
                'ingredient_item' => 'Beef tendons (koyor), sweet soy sauce, palm sugar, spices, and sea salt',
                'netweight_item' => '150g',
                'contain_item' => '-',
                'costprice_item' => 20000,
                'picture_item' => 'lapis-daging-koyor.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-OSU',
                'name_item' => 'Nyam Otak Sapi Ungkep',
                'description_item' => 'Beef brains cooked using the steaming technique with special spices until perfectly infused. Creamy and savory texture.',
                'ingredient_item' => 'Beef brain, spices, sea salt',
                'netweight_item' => '100g',
                'contain_item' => '-',
                'costprice_item' => 35000,
                'picture_item' => 'otak-sapi-ungkep.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-PP',
                'name_item' => 'Nyam Pancake Pisang',
                'description_item' => 'Pancake made from ripe bananas, served with a drizzle of honey.',
                'ingredient_item' => 'Bananas, flour, eggs, honey',
                'netweight_item' => '150g',
                'contain_item' => '-',
                'costprice_item' => 15000,
                'picture_item' => 'pancake-pisang.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-PB',
                'name_item' => 'Nyam Panna Baby',
                'description_item' => 'Special panna cotta for babies',
                'ingredient_item' => 'Milk, natural flavoring',
                'netweight_item' => '50g',
                'contain_item' => '-',
                'costprice_item' => 10000,
                'picture_item' => 'panna-baby.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-SK',
                'name_item' => 'Nyam Soto Kikil',
                'description_item' => 'Traditional Indonesian beef soup with a rich and savory broth.',
                'ingredient_item' => 'Beef, spices, herbs',
                'netweight_item' => '100g',
                'contain_item' => 'Protein, vitamins',
                'costprice_item' => 20000,
                'picture_item' => 'soto-kikil.jpg',
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-PUBI',
                'name_item' => 'Nyam Pancake Ubi',
                'description_item' => null,
                'ingredient_item' => null,
                'netweight_item' => null,
                'contain_item' => null,
                'costprice_item' => 16500,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-MCS',
                'name_item' => 'Nyam Mini Ciki Sausage',
                'description_item' => null,
                'ingredient_item' => null,
                'netweight_item' => null,
                'contain_item' => null,
                'costprice_item' => 24500,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'company_id' => 1,
                'code_item' => 'NY-PBC',
                'name_item' => 'Nyam Panna Baby Coklat',
                'description_item' => null,
                'ingredient_item' => null,
                'netweight_item' => null,
                'contain_item' => null,
                'costprice_item' => 10000,
                'picture_item' => null,
                'status_item' => 'active',
                'created_at' => now(),
                'updated_at' => now()
            ],

            
        ];

        foreach ($items as $item) {
            DB::table('master_items')->insert($item);
        }

        // Insert ke master_items_details untuk harga jual berdasarkan customer type
        $itemDetails = [

            // deep sleep
            ['item_id' => 1, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 1, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 2, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 2, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 3, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 3, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 4, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],

            // joy 
            ['item_id' => 5, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 5, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 6, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 6, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 7, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 7, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 8, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],
            
            // cough
            ['item_id' => 9, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 9, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 10, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 10, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 11, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 11, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 12, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],

            // bye bugs
            ['item_id' => 13, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 13, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 14, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 14, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 15, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 15, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            
            //gimme food
            ['item_id' => 16, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 16, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 17, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 17, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 18, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 18, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 19, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],
            
            // tummy calmer
            ['item_id' => 20, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 20, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 21, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 21, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 22, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 22, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 23, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],

            // ldr booster
            ['item_id' => 24, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 24, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 25, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 25, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 26, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 26, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 27, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],

            // massage your baby
            ['item_id' => 28, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 28, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 29, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 29, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 30, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 30, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 31, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],

            // immboost
            ['item_id' => 32, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 38500],
            ['item_id' => 32, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 27000],
            ['item_id' => 33, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 90000],
            ['item_id' => 33, 'customer_type_id' => 3, 'cost_price' => 25000, 'sell_price' => 63000],
            ['item_id' => 34, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 275000],
            ['item_id' => 34, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 192000],
            ['item_id' => 35, 'customer_type_id' => 4, 'cost_price' => 100000, 'sell_price' => 180000],

            // Healo
            ['item_id' => 36, 'customer_type_id' => 1, 'cost_price' => 8000, 'sell_price' => 25000],
            ['item_id' => 36, 'customer_type_id' => 3, 'cost_price' => 8000, 'sell_price' => 17500],
            ['item_id' => 37, 'customer_type_id' => 1, 'cost_price' => 8000, 'sell_price' => 25000],
            ['item_id' => 37, 'customer_type_id' => 3, 'cost_price' => 8000, 'sell_price' => 17500],
            ['item_id' => 38, 'customer_type_id' => 1, 'cost_price' => 8000, 'sell_price' => 25000],
            ['item_id' => 38, 'customer_type_id' => 3, 'cost_price' => 8000, 'sell_price' => 17500],
            ['item_id' => 39, 'customer_type_id' => 1, 'cost_price' => 8000, 'sell_price' => 25000],
            ['item_id' => 39, 'customer_type_id' => 3, 'cost_price' => 8000, 'sell_price' => 17500],
            ['item_id' => 40, 'customer_type_id' => 1, 'cost_price' => 27000, 'sell_price' => 70000],
            ['item_id' => 40, 'customer_type_id' => 3, 'cost_price' => 27000, 'sell_price' => 49000],
            
            // Mamina 
            ['item_id' => 41, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 25000],
            ['item_id' => 41, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 25000],
            ['item_id' => 42, 'customer_type_id' => 1, 'cost_price' => 18000, 'sell_price' => 43000],
            ['item_id' => 42, 'customer_type_id' => 3, 'cost_price' => 18000, 'sell_price' => 30100],
            ['item_id' => 43, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 65000],
            ['item_id' => 43, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 45500],
            ['item_id' => 44, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 25000],
            ['item_id' => 44, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 25000],
            ['item_id' => 45, 'customer_type_id' => 1, 'cost_price' => 18000, 'sell_price' => 43000],
            ['item_id' => 45, 'customer_type_id' => 3, 'cost_price' => 18000, 'sell_price' => 30100],
            ['item_id' => 46, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 65000],
            ['item_id' => 46, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 45500],
            ['item_id' => 47, 'customer_type_id' => 1, 'cost_price' => 12000, 'sell_price' => 25000],
            ['item_id' => 47, 'customer_type_id' => 3, 'cost_price' => 12000, 'sell_price' => 25000],
            ['item_id' => 48, 'customer_type_id' => 1, 'cost_price' => 18000, 'sell_price' => 43000],
            ['item_id' => 48, 'customer_type_id' => 3, 'cost_price' => 18000, 'sell_price' => 30100],
            ['item_id' => 49, 'customer_type_id' => 1, 'cost_price' => 30000, 'sell_price' => 65000],
            ['item_id' => 49, 'customer_type_id' => 3, 'cost_price' => 30000, 'sell_price' => 45500],
            ['item_id' => 50, 'customer_type_id' => 1, 'cost_price' => 5000, 'sell_price' => 20000],
            ['item_id' => 50, 'customer_type_id' => 3, 'cost_price' => 5000, 'sell_price' => 20000],
            
            // Customer type 1 (Regular customer) - Nyam
            ['item_id' => 51, 'customer_type_id' => 1, 'cost_price' => 22000, 'sell_price' => 31000],
            ['item_id' => 52, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 30000],
            ['item_id' => 53, 'customer_type_id' => 1, 'cost_price' => 15000, 'sell_price' => 26000],
            ['item_id' => 54, 'customer_type_id' => 1, 'cost_price' => 19000, 'sell_price' => 30800],
            ['item_id' => 55, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 30000],
            ['item_id' => 56, 'customer_type_id' => 1, 'cost_price' => 16000, 'sell_price' => 33000],
            ['item_id' => 57, 'customer_type_id' => 1, 'cost_price' => 15000, 'sell_price' => 25000],
            ['item_id' => 58, 'customer_type_id' => 1, 'cost_price' => 10000, 'sell_price' => 19500],
            ['item_id' => 59, 'customer_type_id' => 1, 'cost_price' => 17000, 'sell_price' => 27000],
            ['item_id' => 60, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 35000],
            ['item_id' => 61, 'customer_type_id' => 1, 'cost_price' => 13200, 'sell_price' => 21500],
            ['item_id' => 62, 'customer_type_id' => 1, 'cost_price' => 13200, 'sell_price' => 21500],
            ['item_id' => 63, 'customer_type_id' => 1, 'cost_price' => 13200, 'sell_price' => 21500],
            ['item_id' => 64, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 35000],
            ['item_id' => 65, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 32500],
            ['item_id' => 66, 'customer_type_id' => 1, 'cost_price' => 25000, 'sell_price' => 33000],
            ['item_id' => 67, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 35000],
            ['item_id' => 68, 'customer_type_id' => 1, 'cost_price' => 35000, 'sell_price' => 46000],
            ['item_id' => 69, 'customer_type_id' => 1, 'cost_price' => 15000, 'sell_price' => 25000],
            ['item_id' => 70, 'customer_type_id' => 1, 'cost_price' => 10000, 'sell_price' => 15000],
            ['item_id' => 71, 'customer_type_id' => 1, 'cost_price' => 20000, 'sell_price' => 35000],
            ['item_id' => 72, 'customer_type_id' => 1, 'cost_price' => 16500, 'sell_price' => 30000],
            ['item_id' => 73, 'customer_type_id' => 1, 'cost_price' => 24500, 'sell_price' => 35000],
            ['item_id' => 74, 'customer_type_id' => 1, 'cost_price' => 10000, 'sell_price' => 15000],
            ['item_id' => 75, 'customer_type_id' => 1, 'cost_price' => 16500, 'sell_price' => 30000],
            ['item_id' => 76, 'customer_type_id' => 1, 'cost_price' => 24500, 'sell_price' => 35000],
            ['item_id' => 77, 'customer_type_id' => 1, 'cost_price' => 10000, 'sell_price' => 15000],
            
     ];

        foreach ($itemDetails as $detail) {
            DB::table('master_items_details')->insert(array_merge($detail, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }

        // Insert ke master_items_stock untuk stok
        $stockData = [
            // Gentle Baby Stock
            ['item_id' => 1, 'inventory_id' => 1, 'stock' => 15],
            ['item_id' => 2, 'inventory_id' => 1, 'stock' => 8],
            ['item_id' => 3, 'inventory_id' => 1, 'stock' => 20],
            ['item_id' => 4, 'inventory_id' => 1, 'stock' => 12],
            ['item_id' => 5, 'inventory_id' => 1, 'stock' => 18],
            ['item_id' => 6, 'inventory_id' => 1, 'stock' => 15],
            ['item_id' => 7, 'inventory_id' => 1, 'stock' => 16],
            ['item_id' => 8, 'inventory_id' => 1, 'stock' => 13],
            ['item_id' => 9, 'inventory_id' => 1, 'stock' => 11],
            ['item_id' => 10, 'inventory_id' => 1, 'stock' => 11],
            ['item_id' => 11, 'inventory_id' => 1, 'stock' => 11],
            ['item_id' => 12, 'inventory_id' => 1, 'stock' => 11],
            ['item_id' => 13, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 14, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 15, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 16, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 17, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 18, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 19, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 20, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 21, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 22, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 23, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 24, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 25, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 26, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 27, 'inventory_id' => 1, 'stock' => 30],
            ['item_id' => 28, 'inventory_id' => 1, 'stock' => 20],
            ['item_id' => 29, 'inventory_id' => 1, 'stock' => 26],
            ['item_id' => 30, 'inventory_id' => 1, 'stock' => 35],
            ['item_id' => 31, 'inventory_id' => 1, 'stock' => 40],
            ['item_id' => 32, 'inventory_id' => 1, 'stock' => 28],
            ['item_id' => 33, 'inventory_id' => 1, 'stock' => 32],
            ['item_id' => 34, 'inventory_id' => 1, 'stock' => 30],
            ['item_id' => 35, 'inventory_id' => 1, 'stock' => 27],
            ['item_id' => 36, 'inventory_id' => 1, 'stock' => 50],
            ['item_id' => 37, 'inventory_id' => 1, 'stock' => 45],
            ['item_id' => 38, 'inventory_id' => 1, 'stock' => 60],
            ['item_id' => 39, 'inventory_id' => 1, 'stock' => 38],
            ['item_id' => 40, 'inventory_id' => 1, 'stock' => 42],
            ['item_id' => 41, 'inventory_id' => 1, 'stock' => 55],
            ['item_id' => 42, 'inventory_id' => 1, 'stock' => 48],
            ['item_id' => 43, 'inventory_id' => 1, 'stock' => 70],
            ['item_id' => 44, 'inventory_id' => 1, 'stock' => 40],
            ['item_id' => 45, 'inventory_id' => 1, 'stock' => 36],
            ['item_id' => 46, 'inventory_id' => 1, 'stock' => 65],
            ['item_id' => 47, 'inventory_id' => 1, 'stock' => 65],
            ['item_id' => 48, 'inventory_id' => 1, 'stock' => 65],
            ['item_id' => 49, 'inventory_id' => 1, 'stock' => 36],
            ['item_id' => 50, 'inventory_id' => 1, 'stock' => 44],
            ['item_id' => 51, 'inventory_id' => 1, 'stock' => 30],
            ['item_id' => 52, 'inventory_id' => 1, 'stock' => 38],
            ['item_id' => 53, 'inventory_id' => 1, 'stock' => 28],
            ['item_id' => 54, 'inventory_id' => 1, 'stock' => 50],
            ['item_id' => 55, 'inventory_id' => 1, 'stock' => 75],
            ['item_id' => 56, 'inventory_id' => 1, 'stock' => 33],
            ['item_id' => 57, 'inventory_id' => 1, 'stock' => 60],
            ['item_id' => 58, 'inventory_id' => 1, 'stock' => 45],
            ['item_id' => 59, 'inventory_id' => 1, 'stock' => 75],
            ['item_id' => 60, 'inventory_id' => 1, 'stock' => 26],
            ['item_id' => 61, 'inventory_id' => 1, 'stock' => 20],
            ['item_id' => 62, 'inventory_id' => 1, 'stock' => 15],
            ['item_id' => 63, 'inventory_id' => 1, 'stock' => 18],
            ['item_id' => 64, 'inventory_id' => 1, 'stock' => 22],
            ['item_id' => 65, 'inventory_id' => 1, 'stock' => 17],
            ['item_id' => 66, 'inventory_id' => 1, 'stock' => 19],
            ['item_id' => 67, 'inventory_id' => 1, 'stock' => 16],
            ['item_id' => 68, 'inventory_id' => 1, 'stock' => 14],
            ['item_id' => 69, 'inventory_id' => 1, 'stock' => 13],
            ['item_id' => 70, 'inventory_id' => 1, 'stock' => 25],
            ['item_id' => 71, 'inventory_id' => 1, 'stock' => 10],
            ['item_id' => 72, 'inventory_id' => 1, 'stock' => 22],
            ['item_id' => 73, 'inventory_id' => 1, 'stock' => 17],
            ['item_id' => 74, 'inventory_id' => 1, 'stock' => 19],
            ['item_id' => 75, 'inventory_id' => 1, 'stock' => 16],
            ['item_id' => 76, 'inventory_id' => 1, 'stock' => 14],
        ];

        foreach ($stockData as $stock) {
            DB::table('master_items_stock')->insert(array_merge($stock, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }

        // Insert ke master_items_categories untuk kategori produk
        $categoryData = [
            // Gentle Baby - Category ID 1 (gentle-baby)
            ['categories_id' => 1, 'item_id' => '1'],
            ['categories_id' => 1, 'item_id' => '2'],
            ['categories_id' => 1, 'item_id' => '3'],
            ['categories_id' => 1, 'item_id' => '4'],
            ['categories_id' => 1, 'item_id' => '5'],
            ['categories_id' => 1, 'item_id' => '6'],
            ['categories_id' => 1, 'item_id' => '7'],
            ['categories_id' => 1, 'item_id' => '8'],
            ['categories_id' => 1, 'item_id' => '9'],
            ['categories_id' => 1, 'item_id' => '10'],
            ['categories_id' => 1, 'item_id' => '11'],
            ['categories_id' => 1, 'item_id' => '12'],
            ['categories_id' => 1, 'item_id' => '12'],
            ['categories_id' => 1, 'item_id' => '13'],
            ['categories_id' => 1, 'item_id' => '14'],
            ['categories_id' => 1, 'item_id' => '15'],
            ['categories_id' => 1, 'item_id' => '16'],
            ['categories_id' => 1, 'item_id' => '17'],
            ['categories_id' => 1, 'item_id' => '18'],
            ['categories_id' => 1, 'item_id' => '19'],
            ['categories_id' => 1, 'item_id' => '20'],
            ['categories_id' => 1, 'item_id' => '21'],
            ['categories_id' => 1, 'item_id' => '22'],
            ['categories_id' => 1, 'item_id' => '23'],
            ['categories_id' => 1, 'item_id' => '24'],
            ['categories_id' => 1, 'item_id' => '25'],
            ['categories_id' => 1, 'item_id' => '26'],
            ['categories_id' => 1, 'item_id' => '26'],
            ['categories_id' => 1, 'item_id' => '28'],
            ['categories_id' => 1, 'item_id' => '29'],
            ['categories_id' => 1, 'item_id' => '30'],
            ['categories_id' => 1, 'item_id' => '31'],
            ['categories_id' => 1, 'item_id' => '32'],
            ['categories_id' => 1, 'item_id' => '33'],
            ['categories_id' => 1, 'item_id' => '34'],
            ['categories_id' => 1, 'item_id' => '35'],
            
            ['categories_id' => 1, 'item_id' => '36'],
            ['categories_id' => 1, 'item_id' => '37'],
            ['categories_id' => 1, 'item_id' => '38'],

            // bundling             
            ['categories_id' => 3, 'item_id' => '36'],
            ['categories_id' => 3, 'item_id' => '37'],
            ['categories_id' => 3, 'item_id' => '38'],
            ['categories_id' => 3, 'item_id' => '43'],

            // Healo - Category ID 2
            ['categories_id' => 2, 'item_id' => '39'],
            ['categories_id' => 2, 'item_id' => '40'],
            ['categories_id' => 2, 'item_id' => '41'],
            ['categories_id' => 2, 'item_id' => '42'],

            ['categories_id' => 2, 'item_id' => '43'],
            
            // Mamina - Category ID 8
            ['categories_id' => 8, 'item_id' => '44'],
            ['categories_id' => 8, 'item_id' => '45'],
            ['categories_id' => 8, 'item_id' => '46'],
            ['categories_id' => 8, 'item_id' => '47'],
            ['categories_id' => 8, 'item_id' => '48'],
            ['categories_id' => 8, 'item_id' => '49'],
            ['categories_id' => 8, 'item_id' => '50'],
            ['categories_id' => 8, 'item_id' => '51'],
            ['categories_id' => 8, 'item_id' => '52'],
            ['categories_id' => 8, 'item_id' => '53'],

            // Nyam snack
            ['categories_id' => 6, 'item_id' => '69'],
            ['categories_id' => 6, 'item_id' => '72'],
            ['categories_id' => 6, 'item_id' => '73'],
            ['categories_id' => 6, 'item_id' => '75'],
            ['categories_id' => 6, 'item_id' => '76'],
            ['categories_id' => 6, 'item_id' => '77'],

            // Nyam full meal 
            ['categories_id' => 4, 'item_id' => '54'],
            ['categories_id' => 4, 'item_id' => '55'],
            ['categories_id' => 4, 'item_id' => '56'],
            ['categories_id' => 4, 'item_id' => '57'],
            ['categories_id' => 4, 'item_id' => '58'],
            ['categories_id' => 4, 'item_id' => '59'],
            ['categories_id' => 4, 'item_id' => '61'],
            ['categories_id' => 4, 'item_id' => '62'],
            ['categories_id' => 4, 'item_id' => '63'],
            ['categories_id' => 4, 'item_id' => '68'],
            ['categories_id' => 4, 'item_id' => '70'],
            ['categories_id' => 6, 'item_id' => '71'],
            ['categories_id' => 4, 'item_id' => '72'],
            ['categories_id' => 4, 'item_id' => '74'],
            ['categories_id' => 4, 'item_id' => '75'],
            ['categories_id' => 4, 'item_id' => '76'],
            

            // Nyam ice cream
            ['categories_id' => 5, 'item_id' => '64'],
            ['categories_id' => 5, 'item_id' => '65'],
            ['categories_id' => 5, 'item_id' => '66'],
            ['categories_id' => 5, 'item_id' => '67'],
            
            // Nyam frozen food
            ['categories_id' => 7, 'item_id' => '69'],
        
        ];

        foreach ($categoryData as $category) {
            DB::table('master_items_categories')->insert(array_merge($category, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }
    }
}
