<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MasterContent;
use Carbon\Carbon;

class ProductContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data produk yang sudah ada untuk fresh start
        MasterContent::whereIn('section', ['carousel-produk', 'benefits', 'carousel-variant', 'description'])->delete();

        $now = Carbon::now();

        // ========== 1. CAROUSEL PRODUK DATA ==========
        $carouselProduk = [
            // Gentle Baby Products
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 1',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 2',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 3',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 4',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 5',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 6',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 7',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Gentle Baby - Banner 8',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mamina Products
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 1',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 2',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 3',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 4',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 5',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 6',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 7',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Mamina - Banner 8',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Nyam MPASI Products
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 1',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 2',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 3',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 4',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 5',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 6',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 7',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Nyam - Banner 8',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Healo Products
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 1',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 2',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 3',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 4',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 5',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 6',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 7',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-produk',
                'title' => 'Carousel Produk - Healo - Banner 8',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // ========== 2. BENEFITS DATA ==========
        $benefits = [
            // Gentle Baby Benefits
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Gentle Baby - 1',
                'body' => '100% Bahan Alami',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Gentle Baby - 2',
                'body' => 'Tersertifikasi BPOM',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Gentle Baby - 3',
                'body' => 'Aman untuk Bayi & Ibu Hamil ',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Gentle Baby - 4',
                'body' => 'Formula khusus menjaga kesehatan tubuh dan meredakan keluhan tertentu',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mamina Benefits
            [
                'type_of_page' => 'mamina_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Mamina - 1',
                'body' => '100% bahan alami',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Mamina - 2',
                'body' => 'Resep Keluarga',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Mamina - 3',
                'body' => 'Tanpa Pemanis',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Mamina - 4',
                'body' => 'Tanpa Perisa',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Nyam MPASI Benefits
            [
                'type_of_page' => 'nyam_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Nyam - 1',
                'body' => 'Solusi kegelisahan ibu dalam memberikan asupan seimbang pada masa MPASI.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Nyam - 2',
                'body' => 'Aman, lezat, dan praktis untuk mendukung tumbuh kembang optimal si kecil.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Nyam - 3',
                'body' => 'Dibuat dari bahan pilihan berkualitas tinggi yang diolah secara higienis dan penuh kreativitas.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Nyam - 4',
                'body' => 'Diracik oleh ibu sekaligus praktisi kesehatan, menghasilkan MPASI sehat, padat gizi, dan bercita rasa rumahan.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Healo Benefits
            [
                'type_of_page' => 'healo_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Healo - 1',
                'body' => 'Aman untuk mendukung kesehatan keluarga.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Healo - 2',
                'body' => 'Praktis digunakan sehari-hari dengan kemasan roll-on.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Healo - 3',
                'body' => 'Menjaga kesegaran napas dan melindungi dari polusi ringan.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'benefits',
                'title' => 'Benefit Item - Healo - 4',
                'body' => 'Membantu meredakan keluhan hidung tersumbat, nyeri otot, dan ketidaknyamanan tumbuh gigi.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // ========== 3. CAROUSEL VARIANT DATA ==========
        $carouselVariant = [
            // Gentle Baby Variants
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Bye Bugs',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Cough n Flu',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Deep Sleep',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Gimme Food',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Immboost',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Joy',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - LDR Booster',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Massage Your Baby',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Gentle Baby - Tummy Calmer',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mamina Variants
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Mamina - Belimbing',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Mamina - Jeruk Nipis',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Mamina - Original',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Mamina - Paket',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Nyam MPASI Variants
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Abon Hati Ayam',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Chicken Pudding',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Dori Bumbu Kuning',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Hati Ayam Bumbu Kuning',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Hati Ayam Lengkuas',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Hi.Pro Ice Cream',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Jantung Ayam Ungkep',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Nasi Uduk',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Pancake Pisang',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Nyam - Pasta Bolognese',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Healo Variants
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Healo - Aeris',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Healo - Fresh',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Healo - Stiffin',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Healo - Teething',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Healo - Bundling 1',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'carousel-variant',
                'title' => 'Carousel Varian - Healo - Bundling 2',
                'body' => null,
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // ========== 4. PRODUCT DESCRIPTIONS ==========
        $productDescriptions = [
            [
                'type_of_page' => 'gentle_baby_product',
                'section' => 'benefits',
                'title' => 'Product Description - Gentle Baby',
                'body' => 'Gentle Baby Oil  adalah Minyak Bayi Aromaterapi, kombinasi Essential Oil dan Sunflower Seed Oil untuk kesehatan ibu, bayi dan balita.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'mamina_product',
                'section' => 'benefits',
                'title' => 'Product Description - Mamina',
                'body' => 'Mamina Seduhan herbal dengan khasiat melancarkan ASI dengan komposisi 100% bahan alami, tanpa pemanis dan perisa.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'nyam_product',
                'section' => 'benefits',
                'title' => 'Product Description - Nyam MPASI',
                'body' => 'Hidangan lezat dan bernutrisi tinggi yang dirancang khusus untuk memenuhi kebutuhan gizi si kecil. Terbuat dari bahan pilihan berkualitas, cocok untuk anak dalam masa MPASI.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'type_of_page' => 'healo_product',
                'section' => 'benefits',
                'title' => 'Product Description - Healo',
                'body' => 'HEALO by GentleLiving adalah aromatherapy roll-on alami yang aman untuk seluruh keluarga dari bayi baru lahir hingga dewasa. Dibuat dari 100% carrier oil murni & essential oil Grade A, tanpa tambahan air, tanpa alkohol, tanpa paraben, dan tanpa pewangi sintetis.',
                'image' => null,
                'item_id' => null,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert semua data
        try {
            MasterContent::insert($carouselProduk);
            echo "✅ Carousel Produk data inserted successfully!\n";

            MasterContent::insert($benefits);
            echo "✅ Benefits data inserted successfully!\n";

            MasterContent::insert($carouselVariant);
            echo "✅ Carousel Variant data inserted successfully!\n";

            MasterContent::insert($productDescriptions);
            echo "✅ Product Descriptions inserted successfully!\n";

            echo "\n🎉 All product data has been seeded successfully!\n";
            echo "📊 Total records created: " . (count($carouselProduk) + count($benefits) + count($carouselVariant) + count($productDescriptions)) . "\n";

        } catch (\Exception $e) {
            echo "❌ Error inserting data: " . $e->getMessage() . "\n";
        }
    }
}
